General update to everything.
Dug this script out of my project archive because I have an IRIX system
headed my way (again).  I may write a Makefile to make the installation
and removal of the script, but I'm not too concerned with that right
now.

diff --git a/denag b/denag
--- a/denag
+++ b/denag
@@ -1,33 +1,43 @@
 #!/bin/sh
+#
 # Wrapper for the Silicon Graphics MIPSpro C and C++ compiler.  Disables
 # the license 'nag' screen from stderr.
 #
-# $Id$
+# Copyright 2003-2012 David Cantrell <david.l.cantrell@gmail.com>
 #
-# $Log$
-# Revision 1.2  2003/04/27 19:07:50  dlc-cvs
-# Use "$@" fro argument expansion rather than $*.
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
 #
-# Revision 1.1.1.1  2003/04/27 06:43:53  dlc-cvs
-# Initial import
+#     http://www.apache.org/licenses/LICENSE-2.0
 #
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 #
 
 dump=1
 filter_output() {
-   IFS=`echo`
-   while read line ; do
-      if [ $dump -eq 0 -o -n "`echo $line | grep ERROR`" ]; then
-         echo $line
-      elif [ $dump -eq 2 ] ; then
-         dump=0
-      else
-         tval=`echo $line | grep "Graphics support customer then contact your local support provider."`
-         if [ ! -z "$tval" ]; then
-            dump=2
-         fi
-      fi
-   done
+    IFS=$(echo)
+    while read line ; do
+        if [ ${dump} -eq 0 -o -n "$(echo $line | grep ERROR)" ]; then
+            echo ${line}
+        elif [ ${dump} -eq 2 ] ; then
+            dump=0
+        else
+            tval=$(echo $line | grep "Graphics support customer then contact your local support provider.")
+            [ ! -z "${tval}" ] && dump=2
+        fi
+    done
 }
-/usr/denag/`basename $0` "$@" 3>&2 2>&1 >&3 | filter_output
+
+PROG="$(basename ${0})"
+if [ ! -x /usr/denag/${PROG} ]; then
+    echo "Missing /usr/denag/${PROG}" >&2
+    exit 1
+fi
+
+/usr/denag/${PROG} "$@" 3>&2 2>&1 >&3 | filter_output
 exit 0
